import ICase from "./Case";
import IRat from "./Rat";

export interface IState {
    messages: string[]
    cases: ICase[]
    rats: IRat[]
}

const State: IState = {
    messages: [
        'msg1',
        'msg2',
        'msg2',
        'msg2',
        'msg2',
        'msg2',
        'msg2',
        'msg2',
        'Rat5: Client35j',
        'Rat6: Client3 5j',
        'msg---- #1 #2',
        '#1 msg1',
        '#2 msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2 Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2Divine Raven msg2',
        'Divine Raven msg2',
        '+Rat1: #3 5j',
        '+Rat2: #3 5j',
        'Rat5: #3 stdn',
    ],
    cases: [
        {
            caseNumber: 1,
            cmdr: 'Divine Raven',
            ircNick: 'Divine_Raven',
            systemName: 'Fuelum 123',
            systemLandmark: '',
            language: 'DE',
            platform: 'PC',
            cr: false,
        },
        {
            caseNumber: 2,
            cmdr: 'Client2',
            ircNick: 'Divine_Raven',
            systemName: 'Sol',
            systemLandmark: '100ly from landmark',
            language: 'EN',
            platform: 'XB',
            cr: true,
        },
        {
            caseNumber: 3,
            cmdr: 'Client3',
            ircNick: 'Divine_Raven',
            systemName: 'Fuelum 123',
            systemLandmark: '',
            language: 'EN',
            platform: 'PS',
            cr: false,
        },
        {
            caseNumber: 4,
            cmdr: 'Client4',
            ircNick: 'Divine_Raven',
            systemName: 'Fuelum 123',
            systemLandmark: '',
            language: 'EN',
            platform: 'PC',
            cr: false,
        },
        {
            caseNumber: 5,
            cmdr: 'Client5',
            ircNick: 'Divine_Raven',
            systemName: 'Fuelum 123',
            systemLandmark: '',
            language: 'EN',
            platform: 'PC',
            cr: false,
        },
        {
            caseNumber: 6,
            cmdr: 'Client5',
            ircNick: 'Divine_Raven',
            systemName: 'Fuelum 123',
            systemLandmark: '',
            language: 'EN',
            platform: 'PC',
            cr: false,
        },
        {
            caseNumber: 7,
            cmdr: 'Client5',
            ircNick: 'Divine_Raven',
            systemName: 'Fuelum 123',
            systemLandmark: '',
            language: 'EN',
            platform: 'PC',
            cr: false,
        },
        {
            caseNumber: 8,
            cmdr: 'Client5',
            ircNick: 'Divine_Raven',
            systemName: 'Fuelum 123',
            systemLandmark: '',
            language: 'EN',
            platform: 'PC',
            cr: false,
        },
    ],
    rats: [
        {
            caseNumber: 1,
            cmdr: 'Some Rat 1',
            ircNick: 'DiRaven[PC]',
            fr: true,
            mmc: null,
            wr: false,
            sys: null,
            pos: null,
            bc: null,
            fuel: null,
        },
        {
            caseNumber: 1,
            cmdr: 'Some Rat 2',
            ircNick: 'Rat_2',
            fr: true,
            mmc: null,
            wr: true,
            sys: null,
            pos: null,
            bc: false,
            fuel: null,
        },
        {
            caseNumber: 2,
            cmdr: 'Some Rat 3',
            ircNick: 'Rat_3',
            fr: true,
            mmc: null,
            wr: true,
            sys: null,
            pos: true,
            bc: null,
            fuel: null,
        },
        {
            caseNumber: 2,
            cmdr: 'Some Rat 4',
            ircNick: 'Rat_4',
            fr: true,
            mmc: null,
            wr: false,
            sys: null,
            pos: true,
            bc: null,
            fuel: null,
        },
    ],
};

export default State;
